package josecarlos.analizadorweb.frontend;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.JFrame;
import josecarlos.analizadorweb.archivos.ExportFile;
import josecarlos.analizadorweb.backend.analizadores.Optimizer;
import josecarlos.analizadorweb.backend.tokens.Token;

/**
 *
 * @author emahch
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pack();
    }
    
    private Optional<String> getText(){
        String texto = textoEntrada.getText();
        if (texto == null || texto.isBlank()) {
            return Optional.empty();
        }
        return Optional.of(texto);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        textoEntrada = new javax.swing.JTextArea();
        botonGenerarHTML = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Léxico");
        setMinimumSize(new java.awt.Dimension(800, 500));

        textoEntrada.setColumns(20);
        textoEntrada.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        textoEntrada.setRows(5);
        scrollPane.setViewportView(textoEntrada);

        botonGenerarHTML.setText("Generar HTML");
        botonGenerarHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarHTMLActionPerformed(evt);
            }
        });

        botonReportes.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGenerarHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGenerarHTML)
                    .addComponent(botonReportes))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarHTMLActionPerformed
        Optional<String> texto = getText();
        if (texto.isEmpty()) {
            return;
        }
        List<Token> tokens = new ArrayList<>();
        
        ExportFile exportFile = new ExportFile();
        exportFile.selectPath();
    }//GEN-LAST:event_botonGenerarHTMLActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarHTML;
    private javax.swing.JButton botonReportes;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textoEntrada;
    // End of variables declaration//GEN-END:variables
}
