package josecarlos.analizadorweb.frontend;

import java.util.List;
import java.util.Optional;
import javax.swing.JFrame;
import josecarlos.analizadorweb.backend.Lector;
import josecarlos.analizadorweb.backend.analizadores.utilities.TokenList;
import josecarlos.analizadorweb.backend.tokens.Token;

/**
 *
 * @author emahch
 */
public class FramePrincipal extends javax.swing.JFrame {

    private Lector lector;

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pack();
    }

    private Optional<String> getText() {
        String texto = textoEntrada.getText();
        if (texto == null || texto.isBlank()) {
            return Optional.empty();
        }
        return Optional.of(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        textoEntrada = new javax.swing.JTextArea();
        botonGenerarHTML = new javax.swing.JButton();
        botonVerCodigoOptimizado = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemLimpiar = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemToken = new javax.swing.JMenuItem();
        itemOptimizacion = new javax.swing.JMenuItem();
        itemErrores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Léxico");
        setMinimumSize(new java.awt.Dimension(800, 500));

        textoEntrada.setColumns(20);
        textoEntrada.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        textoEntrada.setRows(5);
        textoEntrada.setText(">>[html]\n<contenedor id=\"showcase\">\n<contenedor class=\"container\">\n<titulo1>Bienvenido a Mi Página<titulo1/>\n<parrafo>Explora nuestro contenido y conoce más sobre\nnosotros.<parrafo/>\n//END\n<contenedor/>\n<contenedor/>");
        textoEntrada.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                textoEntradaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        scrollPane.setViewportView(textoEntrada);

        botonGenerarHTML.setText("Generar HTML");
        botonGenerarHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarHTMLActionPerformed(evt);
            }
        });

        botonVerCodigoOptimizado.setText("Ver código optimizado");

        menuArchivo.setText("Archivo");

        itemLimpiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemLimpiar.setText("Limpiar Entrada");
        itemLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLimpiarActionPerformed(evt);
            }
        });
        menuArchivo.add(itemLimpiar);

        menuBar.add(menuArchivo);

        menuReportes.setText("Reportes");

        itemToken.setText("Tokens");
        itemToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTokenActionPerformed(evt);
            }
        });
        menuReportes.add(itemToken);

        itemOptimizacion.setText("Optimizacion");
        itemOptimizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOptimizacionActionPerformed(evt);
            }
        });
        menuReportes.add(itemOptimizacion);

        itemErrores.setText("Errores");
        itemErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemErroresActionPerformed(evt);
            }
        });
        menuReportes.add(itemErrores);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(botonVerCodigoOptimizado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(botonGenerarHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerCodigoOptimizado)
                    .addComponent(botonGenerarHTML))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGenerarHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarHTMLActionPerformed
        Optional<String> texto = getText();
        if (texto.isEmpty()) {
            return;
        }

        lector = new Lector(textoEntrada.getText());
        TokenList tokenList = lector.generarTokens();
        List<Token> list = tokenList.getTokens();
        for (Token token : list) {
            System.out.println("-> " + token.getToken() + "; " + token.getType() + "; " + token.getLanguage());
        }

//        ExportFile exportFile = new ExportFile();
//        exportFile.selectPath();
    }//GEN-LAST:event_botonGenerarHTMLActionPerformed

    private void itemLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLimpiarActionPerformed
        textoEntrada.setText("");
    }//GEN-LAST:event_itemLimpiarActionPerformed

    private void textoEntradaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textoEntradaCaretPositionChanged
    }//GEN-LAST:event_textoEntradaCaretPositionChanged

    private void itemTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTokenActionPerformed

    private void itemOptimizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOptimizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemOptimizacionActionPerformed

    private void itemErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemErroresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemErroresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenerarHTML;
    private javax.swing.JButton botonVerCodigoOptimizado;
    private javax.swing.JMenuItem itemErrores;
    private javax.swing.JMenuItem itemLimpiar;
    private javax.swing.JMenuItem itemOptimizacion;
    private javax.swing.JMenuItem itemToken;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textoEntrada;
    // End of variables declaration//GEN-END:variables
}
